### ISSUE TITLE
Conflict of `beginning_of_week` and `end_of_week`

### ISSUE THREAD

**Issue by kobaltz** [sachin87/week-of-month#18]
Rails already has a `beginning_of_week` and `end_of_week` method that the `week-of-month` gem is overriding. While this would normally be okay, it breaks existing functionality of being able to declare the week start.

For example, without the `week-of-month` gem, `Date.today.beginning_of_month.beginning_of_week(:sunday)` will return the first calendar day of the month. For the current month of May 2015, this would return the expected April 26th 2015. However, with the `week-of-month` gem added to the Rails project, this then creates an error for `wrong number of arguments (1 for 0)`. 

I suggest either grabbing the `active_support/core_ext/date` and `active_support/core_ext/time` methods if you want this functionality outside of Rails or rename them to avoid the conflict. What are your thoughts?

**Comment by Blackening999** [comment]
That's a game changer of saying goodbye to this library,sad

**Comment by sachin87** [comment]
Methods `beginning_of_week` and `end_of_week` renamed to `starting_of_week` and `ending_of_week`.
