### ISSUE TITLE
Configuring Monday as week start day causes all_mondays_in_month method to return all Tuesdays

### ISSUE THREAD

**Issue by kelvintyb** [sachin87/week-of-month#25]
Please see screenshot below for replication of issue. Will work on a fix when I have time available, and if this is an issue that has not already been fixed in any upcoming releases.

![screen shot 2017-04-17 at 3 01 17 pm](https://cloud.githubusercontent.com/assets/3264337/25081807/237e5a96-237f-11e7-9c50-3b73c5a669ff.png)

**Comment by arpit016** [comment]
@kelvintyb I am also having the same issue. Any fix for it to work?
