### ISSUE TITLE
URGENT! week_of_month no longer work

### ISSUE THREAD

**Issue by Blackening999** [sachin87/week-of-month#27]
*** NoMethodError Exception: undefined method `week_of_month' for Tue, 31 Jan 2012:Date

**Comment by Blackening999** [comment]
@sachin87 I think community appreciates your work on this library, but please be more careful with changes
Thank you!

**Comment by sachin87** [comment]
@Blackening999 I ran the test cases, they work fine. Let me check.

**Comment by sachin87** [comment]
@Blackening999 here is the output of my console, please check

```
2.4.1 :001 > require 'week_of_month'
 => true 
2.4.1 :002 > Date.today.week_of_month
 => 2 

```

I found no issue

**Comment by Blackening999** [comment]
can you publish a new version, please? just add a tag, old version works for me as of now

**Comment by sachin87** [comment]
@Blackening999 I have already pushed the latest version i,e. `1.2.5`, once you add the gem to the gemfile you don't even have to require it.

**Comment by sachin87** [comment]
@Blackening999 please respond, is it working for you with version `1.2.5`?

**Comment by sachin-metacube** [comment]
should I close this issue if it's working for you?

**Comment by sachin87** [comment]
@Blackening999 I am closing this issue as I have tested and its working and I have not got any response from you on this.
